--红龙-羽蛇神
function c11113099.initial_effect(c)
	c:EnableReviveLimit()
	--spsummon condition
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetCode(EFFECT_SPSUMMON_CONDITION)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_CANNOT_DISABLE_SPSUMMON)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	c:RegisterEffect(e2)
	--xyz
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_SPSUMMON_PROC)
	e3:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	e3:SetRange(LOCATION_EXTRA)
	e3:SetCondition(c11113099.xyzcon)
	e3:SetOperation(c11113099.xyzop)
	e3:SetValue(SUMMON_TYPE_XYZ)
	c:RegisterEffect(e3)
	--cannot be target
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE)
	e5:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e5:SetCode(EFFECT_CANNOT_BE_BATTLE_TARGET)
	e5:SetRange(LOCATION_MZONE)
	e5:SetValue(aux.imval1)
	c:RegisterEffect(e5)
	--effect copy
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e6:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e6:SetCode(EVENT_SPSUMMON_SUCCESS)
	e6:SetCondition(c11113099.effcon)
	e6:SetOperation(c11113099.effop)
	c:RegisterEffect(e6)
end
function c11113099.ovfilter(c,sc)
	return c:GetLevel()>=5 and c:IsFaceup() and c:IsRace(RACE_DRAGON+RACE_WYRM) and c:IsCanBeXyzMaterial(sc)
end
function c11113099.ovfilter1(c,tp,g,sc)
	return c:IsType(TYPE_TUNER) and g:IsExists(c11113099.ovfilter2,1,c,tp,c,sc,c:GetLevel())
end
function c11113099.ovfilter2(c,tp,mc,sc,lv)
    local sg=Group.FromCards(c,mc)
	return c:GetLevel()==lv and Duel.GetLocationCountFromEx(tp,tp,sg,sc)>0
end
function c11113099.ovfilter3(c)
	return c:GetLevel()<=8 and c:IsType(TYPE_SYNCHRO) and c:IsRace(RACE_DRAGON+RACE_WYRM) and c:IsAbleToGraveAsCost()
end
function c11113099.xyzcon(e,c)
	if c==nil then return true end
	local tp=c:GetControler()
	local g=Duel.GetMatchingGroup(c11113099.ovfilter,tp,LOCATION_MZONE,0,nil,c)
	local g2=Duel.GetMatchingGroup(c11113099.ovfilter3,tp,LOCATION_EXTRA,0,nil)
	return g:IsExists(c11113099.ovfilter1,1,nil,tp,g,c)
	    and g2:GetClassCount(Card.GetCode)>5
end
function c11113099.xyzop(e,tp,eg,ep,ev,re,r,rp,c)
    Duel.SelectOption(tp,aux.Stringid(11113099,0))
	Duel.SelectOption(1-tp,aux.Stringid(11113099,0))
	local g=Duel.GetMatchingGroup(c11113099.ovfilter,tp,LOCATION_MZONE,0,nil,c)
	local sg=Duel.GetMatchingGroup(c11113099.ovfilter3,tp,LOCATION_EXTRA,0,nil)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
	local sg1=sg:Select(tp,1,1,nil)
	sg:Remove(Card.IsCode,nil,sg1:GetFirst():GetCode())
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
	local sg2=sg:Select(tp,1,1,nil)
	sg:Remove(Card.IsCode,nil,sg2:GetFirst():GetCode())
	sg1:Merge(sg2)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
	local sg3=sg:Select(tp,1,1,nil)
	sg:Remove(Card.IsCode,nil,sg3:GetFirst():GetCode())
	sg1:Merge(sg3)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
	local sg4=sg:Select(tp,1,1,nil)
	sg:Remove(Card.IsCode,nil,sg4:GetFirst():GetCode())
	sg1:Merge(sg4)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
    local sg5=sg:Select(tp,1,1,nil)
	sg:Remove(Card.IsCode,nil,sg5:GetFirst():GetCode())
	sg1:Merge(sg5)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
	local sg6=sg:Select(tp,1,1,nil)
	sg1:Merge(sg6)
	Duel.SendtoGrave(sg1,REASON_COST)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_XMATERIAL)
	local g1=g:FilterSelect(tp,c11113099.ovfilter1,1,1,nil,tp,g,c)
	local mc=g1:GetFirst()
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_XMATERIAL)
	local g2=g:FilterSelect(tp,c11113099.ovfilter2,1,1,mc,tp,mc,c,mc:GetLevel())
	g1:Merge(g2)
	c:SetMaterial(g1)
	Duel.Overlay(c,g1)
end
function c11113099.effcon(e)
	return e:GetHandler():GetSummonType()==SUMMON_TYPE_XYZ
end
function c11113099.effop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(11113099,2))
	e1:SetCategory(CATEGORY_TODECK)
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetCountLimit(1)
	e1:SetRange(LOCATION_MZONE)
	e1:SetTarget(c11113099.cptg)
	e1:SetOperation(c11113099.cpop)
	e1:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e1)
end
function c11113099.cpfilter(c)
	return c:IsLevelBelow(8) and c:IsType(TYPE_SYNCHRO) and c:IsRace(RACE_DRAGON+RACE_WYRM) and c:IsAbleToExtra()
end
function c11113099.cptg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return chkc:IsControler(tp) and chkc:IsLocation(LOCATION_GRAVE) and c11113099.cpfilter(chkc) end
	if chk==0 then return Duel.IsExistingTarget(c11113099.cpfilter,tp,LOCATION_GRAVE,0,1,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TARGET)
	local g=Duel.SelectTarget(tp,c11113099.cpfilter,tp,LOCATION_GRAVE,0,1,1,nil)
	Duel.SetOperationInfo(0,CATEGORY_TODECK,g,1,0,0)
	Duel.SetChainLimit(aux.FALSE)
end
function c11113099.cpop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstTarget()
	if tc:IsRelateToEffect(e) and Duel.SendtoDeck(tc,nil,2,REASON_EFFECT)~=0 and tc:IsLocation(LOCATION_EXTRA) then
	    if c:IsRelateToEffect(e) and c:IsFaceup() then
			local code=tc:GetOriginalCode()
			local atk=tc:GetBaseAttack()
			local e1=Effect.CreateEffect(c)
			e1:SetType(EFFECT_TYPE_SINGLE)
			e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
			e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
			e1:SetCode(EFFECT_CHANGE_CODE)
			e1:SetValue(code)
			c:RegisterEffect(e1)
			local e2=e1:Clone()
			e2:SetCode(EFFECT_SET_BASE_ATTACK)
			e2:SetValue(atk)
			c:RegisterEffect(e2)
			c:CopyEffect(code,RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END,1)
		end	
	end
end