--神盾 布罗迪亚
local m=47501004
local cm=_G["c"..m]
function c47501004.initial_effect(c)
    --synchro summon
    aux.AddSynchroProcedure(c,aux.FilterBoolFunction(Card.IsSynchroType,TYPE_SYNCHRO),aux.NonTuner(c47501004.synfilter2),2)
    c:EnableReviveLimit() 
    --spsummon condition
    local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_SINGLE)
    e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
    e1:SetCode(EFFECT_SPSUMMON_CONDITION)
    e1:SetValue(aux.synlimit)
    c:RegisterEffect(e1)    
    --shield
    local e1=Effect.CreateEffect(c)
    e1:SetDescription(aux.Stringid(47501004,0))
    e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
    e1:SetCode(EVENT_SPSUMMON_SUCCESS)
    e1:SetCondition(c47501004.gdcon)
    e1:SetOperation(c47501004.gdop)
    c:RegisterEffect(e1) 
    local e2=Effect.CreateEffect(c)
    e2:SetDescription(aux.Stringid(47501004,0))
    e2:SetType(EFFECT_TYPE_FIELD)
    e2:SetCode(EFFECT_IMMUNE_EFFECT)
    e2:SetRange(LOCATION_MZONE)
    e2:SetProperty(EFFECT_FLAG_SET_AVAILABLE)
    e2:SetTargetRange(LOCATION_MZONE,0)
    e2:SetTarget(c47501004.indtg)
    e2:SetValue(c47501004.efilter2)
    c:RegisterEffect(e2)
    local e3=Effect.CreateEffect(c)
    e3:SetType(EFFECT_TYPE_FIELD)
    e3:SetCode(EFFECT_DEFENSE_ATTACK)
    e3:SetRange(LOCATION_MZONE)
    e3:SetTargetRange(LOCATION_MZONE,0)
    e3:SetValue(1)
    c:RegisterEffect(e3)
    --diseffect
    local e4=Effect.CreateEffect(c)
    e4:SetDescription(aux.Stringid(47501004,1))
    e4:SetType(EFFECT_TYPE_QUICK_O)
    e4:SetCode(EVENT_FREE_CHAIN)
    e4:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_NO_TURN_RESET)
    e4:SetRange(LOCATION_MZONE)
    e4:SetOperation(c47501004.immop)
    c:RegisterEffect(e4)
end
function c47501004.synfilter2(c)
    return c:IsType(TYPE_SYNCHRO+TYPE_FUSION)
end
function c47501004.gdcon(e,tp,eg,ep,ev,re,r,rp)
    return e:GetHandler():IsSummonType(SUMMON_TYPE_SYNCHRO)
end
function c47501004.gdop(e,tp,eg,ep,ev,re,r,rp)
    local e1=Effect.CreateEffect(e:GetHandler())
    e1:SetType(EFFECT_TYPE_FIELD)
    e1:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
    e1:SetTargetRange(LOCATION_MZONE,0)
    e1:SetReset(RESET_PHASE+PHASE_END)
    e1:SetValue(1)
    Duel.RegisterEffect(e1,tp)
    local e3=Effect.CreateEffect(c)
    e3:SetType(EFFECT_TYPE_FIELD)
    e3:SetCode(EFFECT_IMMUNE_EFFECT)
    e3:SetRange(LOCATION_MZONE)
    e3:SetProperty(EFFECT_FLAG_SET_AVAILABLE)
    e3:SetTargetRange(LOCATION_MZONE,0)
    e3:SetValue(c47501004.efilter1)
    e3:SetReset(RESET_PHASE+PHASE_END)
    Duel.RegisterEffect(e3,tp)
end
function c47501004.efilter1(e,re)
    return e:GetOwnerPlayer()~=re:GetOwnerPlayer()
end
function c47501004.indtg(e,c)
    local te,g=Duel.GetChainInfo(0,CHAININFO_TRIGGERING_EFFECT,CHAININFO_TARGET_CARDS)
    return not te or not te:IsHasProperty(EFFECT_FLAG_CARD_TARGET) or not g or not g:IsContains(c)
end
function c47501004.efilter2(e,te)
    return te:GetOwnerPlayer()~=e:GetHandlerPlayer()
end
function c47501004.immop(e,tp,eg,ep,ev,re,r,rp)
    local e1=Effect.CreateEffect(e:GetHandler())
    e1:SetType(EFFECT_TYPE_FIELD)
    e1:SetCode(EFFECT_IMMUNE_EFFECT)
    e1:SetTargetRange(0,LOCATION_ONFIELD)
    e1:SetReset(RESET_PHASE+PHASE_END)
    e1:SetValue(c47501004.efilter3)
    Duel.RegisterEffect(e1,tp)
end
function c47501004.efilter3(e,te)
    return te:GetOwnerPlayer()~=e:GetOwnerPlayer()
end 