--守护星曜·遁甲
function c66915004.initial_effect(c)
    c:SetUniqueOnField(1,0,66915004)
    local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_ACTIVATE)
    e1:SetCode(EVENT_FREE_CHAIN)
    c:RegisterEffect(e1)
    local e2=Effect.CreateEffect(c)
    e2:SetType(EFFECT_TYPE_SINGLE)
    e2:SetRange(LOCATION_SZONE)
    e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
    e2:SetCode(EFFECT_LINK_SPELL_KOISHI)
    e2:SetValue(LINK_MARKER_TOP+LINK_MARKER_TOP_RIGHT)
    c:RegisterEffect(e2)    
    --target
    local e22=Effect.CreateEffect(c)
    e22:SetType(EFFECT_TYPE_FIELD)
    e22:SetRange(LOCATION_MZONE)
    e22:SetTargetRange(0,LOCATION_MZONE)
    e22:SetCode(EFFECT_CANNOT_SELECT_BATTLE_TARGET)
    e22:SetValue(c66915004.atlimit)
    local e5=Effect.CreateEffect(c)
    e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
    e5:SetRange(LOCATION_SZONE)
    e5:SetTargetRange(LOCATION_MZONE,0)
    e5:SetTarget(c66915004.eftg)
    e5:SetLabelObject(e22)
    --spsummon limit
    local e2=Effect.CreateEffect(c)
    e2:SetType(EFFECT_TYPE_FIELD)
    e2:SetRange(LOCATION_SZONE)
    e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
    e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
    e2:SetTargetRange(1,0)
    e2:SetTarget(c66915004.sumlimit)
    c:RegisterEffect(e2)
    local e11=Effect.CreateEffect(c)
    e11:SetType(EFFECT_TYPE_FIELD)
    e11:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
    e11:SetRange(LOCATION_SZONE)
    e11:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
    e11:SetTarget(c66915004.tgtg)
    e11:SetValue(1)
    c:RegisterEffect(e11)
end
function c66915004.atlimit(e,c)
    return c~=e:GetHandler()
end
function c66915004.sumlimit(e,c,sump,sumtype,sumpos,targetp)
    return c:IsLocation(LOCATION_EXTRA) and not c:IsSetCard(0x1374)
end
function c66915004.eftg(e,c)
    local lg=e:GetHandler():GetLinkedGroup()
    return c:IsType(TYPE_EFFECT) and c:IsSetCard(0x1374) and lg:IsContains(c)
end
function c66915004.tgtg(e,c)
    return e:GetHandler():GetLinkedGroup():IsContains(c) and c:IsType(TYPE_EFFECT) and c:IsSetCard(0x1374)
end