--失落终端 兵神希儿
function c75646517.initial_effect(c)
	c:SetUniqueOnField(1,0,75646517)
	--link summon
	aux.AddLinkProcedure(c,nil,2)
	c:EnableReviveLimit()
	--effect gain
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_UPDATE_ATTACK)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetValue(1000)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_UPDATE_DEFENSE)   
	--cannot be battle target
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetCode(EFFECT_CANNOT_SELECT_BATTLE_TARGET)
	e4:SetRange(LOCATION_MZONE)
	e4:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e4:SetValue(c75646517.etarget)
	--immune effect
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_FIELD)
	e5:SetCode(EFFECT_IMMUNE_EFFECT)
	e5:SetRange(LOCATION_MZONE)
	e5:SetTargetRange(LOCATION_MZONE,0)
	e5:SetTarget(c75646517.etarget)
	e5:SetValue(c75646517.efilter)
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e6:SetRange(LOCATION_MZONE)
	e6:SetTargetRange(LOCATION_MZONE,0)
	e6:SetTarget(c75646517.eftg)
	e6:SetLabelObject(e1)
	c:RegisterEffect(e6)
	local e7=e6:Clone()
	e7:SetLabelObject(e2)
	c:RegisterEffect(e7)
	local e9=e7:Clone()
	e9:SetLabelObject(e4)
	c:RegisterEffect(e9)
	local e10=e9:Clone()
	e10:SetLabelObject(e5)
	c:RegisterEffect(e10)
	--actlimit
	local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_FIELD)
	e11:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e11:SetCode(EFFECT_CANNOT_ACTIVATE)
	e11:SetRange(LOCATION_MZONE)
	e11:SetTargetRange(0,1)
	e11:SetValue(c75646517.aclimit)
	e11:SetCondition(c75646517.actcon)
	c:RegisterEffect(e11)
end
function c75646517.eftg(e,c)
	return c:IsFaceup() and not c:IsCode(75646517)
end
function c75646517.etarget(e,c)
	return c:IsCode(75646517)
end
function c75646517.efilter(e,re)
	return re:GetOwnerPlayer()~=e:GetHandlerPlayer()
end
function c75646517.aclimit(e,re,tp)
	return not re:GetHandler():IsImmuneToEffect(e)
end
function c75646517.actcon(e)
	local a=Duel.GetAttacker()
	return a and a:IsControler(e:GetHandlerPlayer())
end